[package]
name = "zenclash-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "zenclash"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
futures-util.workspace = true
gpui-kit.workspace = true
parking_lot.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tray-icon.workspace = true
zenclash-core = { path = "../zenclash-core" }
zenclash-i18n.workspace = true

[build-dependencies]
embed-resource = "3.0.12"

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle.workspace = true
windows-sys.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
raw-window-handle.workspace = true
objc2.workspace = true
objc2-app-kit = { workspace = true, features = [
    "std",
    "NSApplication",
    "NSButton",
    "NSImage",
    "NSResponder",
    "NSStatusBarButton",
    "NSStatusItem",
    "NSView",
    "NSWindow",
] }
objc2-foundation = { workspace = true, features = [
    "std",
    "NSDate",
    "NSObjCRuntime",
    "NSObject",
    "NSRunLoop",
    "NSString",
    "NSTimer",
] }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
zenclash-core = { path = "../zenclash-core", features = ["test-support"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18.2"
