use std::{
    ffi::OsString,
    fs::{File, OpenOptions},
    io,
    os::windows::fs::{MetadataExt, OpenOptionsExt},
    path::Path,
};

use windows_sys::Win32::{
    Foundation::{ERROR_CANCELLED, WAIT_FAILED, WAIT_OBJECT_0, WAIT_TIMEOUT},
    Storage::FileSystem::{
        FILE_ATTRIBUTE_REPARSE_POINT, FILE_FLAG_OPEN_REPARSE_POINT, FILE_SHARE_READ,
    },
    System::Threading::{GetExitCodeProcess, WaitForSingleObject},
    UI::{
        Shell::{SEE_MASK_FLAG_NO_UI, SEE_MASK_NOCLOSEPROCESS, SHELLEXECUTEINFOW, ShellExecuteExW},
        WindowsAndMessaging::SW_HIDE,
    },
};

use super::{Handle, denied, wide};

/// Pin approved source bytes against replacement during an authorized copy.
pub(crate) fn open_pinned_file(path: &Path) -> io::Result<File> {
    let file = OpenOptions::new()
        .read(true)
        .share_mode(FILE_SHARE_READ)
        .custom_flags(FILE_FLAG_OPEN_REPARSE_POINT)
        .open(path)?;
    let metadata = file.metadata()?;
    if !metadata.is_file() || metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT != 0 {
        return Err(denied("approved artifact is not a regular file"));
    }
    Ok(file)
}

/// Request a fixed service maintenance operation, called on a background thread.
pub(crate) fn request_maintenance(
    action: &str,
    source: &Path,
    arguments: &[OsString],
) -> io::Result<()> {
    if !matches!(action, "install" | "repair" | "uninstall" | "start") {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "unknown service maintenance operation",
        ));
    }
    let _pinned_helper = open_pinned_file(source)?;
    let verb = wide("runas")?;
    let executable = wide(source)?;
    let mut command = quote_argument(std::ffi::OsStr::new(&format!("--{action}")))?;
    for argument in arguments {
        command.push(' ');
        command.push_str(&quote_argument(argument)?);
    }
    let command = wide(command)?;
    let mut info: SHELLEXECUTEINFOW = unsafe { std::mem::zeroed() };
    info.cbSize = std::mem::size_of::<SHELLEXECUTEINFOW>() as u32;
    info.fMask = SEE_MASK_NOCLOSEPROCESS | SEE_MASK_FLAG_NO_UI;
    info.lpVerb = verb.as_ptr();
    info.lpFile = executable.as_ptr();
    info.lpParameters = command.as_ptr();
    info.nShow = SW_HIDE;
    if unsafe { ShellExecuteExW(&mut info) } == 0 {
        return Err(authorization_launch_error(io::Error::last_os_error()));
    }
    if info.hProcess.is_null() {
        return Err(io::Error::new(
            io::ErrorKind::TimedOut,
            "elevated installer process handle unavailable",
        ));
    }
    let process = Handle(info.hProcess);
    loop {
        let wait = unsafe { WaitForSingleObject(process.0, 200) };
        if wait == WAIT_OBJECT_0 {
            break;
        }
        if wait == WAIT_FAILED || wait != WAIT_TIMEOUT {
            return Err(io::Error::new(
                io::ErrorKind::TimedOut,
                "elevated maintenance process outcome could not be observed",
            ));
        }
    }
    let mut exit_code = 0;
    if unsafe { GetExitCodeProcess(process.0, &mut exit_code) } == 0 {
        return Err(io::Error::new(
            io::ErrorKind::TimedOut,
            "elevated maintenance exit status could not be observed",
        ));
    }
    if exit_code != 0 {
        return Err(io::Error::other(format!(
            "elevated maintenance failed ({exit_code})"
        )));
    }
    Ok(())
}

fn authorization_launch_error(error: io::Error) -> io::Error {
    if error.raw_os_error() == Some(ERROR_CANCELLED as i32) {
        crate::installer::authorization_cancelled()
    } else {
        error
    }
}

pub(super) fn quote_argument(value: &std::ffi::OsStr) -> io::Result<String> {
    // Arguments are generated by ZenClash rather than interpreted by a shell.
    // ShellExecute passes this exact string to CommandLineToArgvW parsing.
    let value = value.to_str().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "maintenance argument is not Unicode",
        )
    })?;
    if value.contains('\0') {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "maintenance argument contains NUL",
        ));
    }
    let mut quoted = String::from("\"");
    let mut slashes = 0;
    for character in value.chars() {
        if character == '\\' {
            slashes += 1;
            continue;
        }
        if character == '"' {
            quoted.extend(std::iter::repeat_n('\\', slashes * 2 + 1));
        } else {
            quoted.extend(std::iter::repeat_n('\\', slashes));
        }
        slashes = 0;
        quoted.push(character);
    }
    quoted.extend(std::iter::repeat_n('\\', slashes * 2));
    quoted.push('"');
    Ok(quoted)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maintenance_uac_cancellation_is_distinct_from_failed_authorization() {
        assert_eq!(
            authorization_launch_error(io::Error::from_raw_os_error(1223)).kind(),
            io::ErrorKind::Interrupted,
        );
        assert_ne!(
            authorization_launch_error(io::Error::from_raw_os_error(5)).kind(),
            io::ErrorKind::Interrupted,
        );
    }

    #[test]
    fn maintenance_argument_quotes_embedded_quotes_and_trailing_slashes() {
        assert_eq!(
            quote_argument(std::ffi::OsStr::new("a b\\\"c\\")).unwrap(),
            "\"a b\\\\\\\"c\\\\\""
        );
    }

    #[test]
    fn open_artifact_pins_source_against_modification() {
        let path = std::env::temp_dir().join(format!("zenclash-pinned-{}", std::process::id()));
        std::fs::write(&path, b"approved").unwrap();
        let pinned = open_pinned_file(&path).unwrap();
        assert!(OpenOptions::new().write(true).open(&path).is_err());
        assert!(std::fs::remove_file(&path).is_err());
        drop(pinned);
        std::fs::remove_file(path).unwrap();
    }
}
